"use client";
import { AnimatePresence, motion } from "framer-motion";
import { Star, X } from "lucide-react";
import { useState } from "react";
import { dramas, type Drama } from "@/data/dramas";

export function DramaShelf() {
  const [selected, setSelected] = useState<Drama | null>(null);
  return <section id="dramas" className="section shelf page-width"><div className="section-heading"><p className="eyebrow ink">01 / Выбор Мохинур</p><h2>Дорамы для долгого вечера.</h2><p>Нажмите на постер, чтобы открыть карточку дорамы.</p></div><div className="drama-grid">{dramas.map((drama, index) => <motion.button key={drama.title} className="drama-card" onClick={() => setSelected(drama)} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }}><img src={drama.image} alt="" /><span className="card-shade" /><span className="card-info"><small>{drama.genre}</small><b>{drama.title}</b><span><Star size={13} fill="currentColor" /> {drama.rating}</span></span><span className="favorite">Главная героиня: {drama.character}</span></motion.button>)}</div><AnimatePresence>{selected && <motion.div className="modal-backdrop" onClick={() => setSelected(null)} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.article className="drama-modal" onClick={(event) => event.stopPropagation()} initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 24 }}><img src={selected.image} alt="" /><div><button className="close-button" onClick={() => setSelected(null)} aria-label="Закрыть карточку дорамы"><X /></button><p className="eyebrow ink">{selected.genre}</p><h3>{selected.title}</h3><p>{selected.description}</p><span className="modal-rating"><Star size={15} fill="currentColor" /> {selected.rating} / 10</span><p className="favorite-text">Главная героиня: <b>{selected.character}</b></p></div></motion.article></motion.div>}</AnimatePresence></section>;
}